# Generated by Django 5.2.7 on 2025-12-11 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_message_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
