# Generated by Django 5.2.7 on 2025-11-22 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_status_customuser_mentor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mentor_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
    ]
