# Generated by Django 5.2.7 on 2025-11-11 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency_paths',
            name='mentor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentor_grade',
            name='mentor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentor_grade',
            name='reviewer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentor_grade',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_grades', to='onboarding.tasks'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='generated_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='changed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='new_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='old_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='onboarding.tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='mentor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='path',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_path', to='onboarding.competency_paths'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_badges',
            name='badge',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.badges'),
        ),
        migrations.AlterField(
            model_name='user_badges',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='assigned_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='path',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to='onboarding.competency_paths'),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
