# Generated by Django 5.2.7 on 2025-11-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_competency_paths_mentor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badges',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='competency_paths',
            options={'verbose_name': 'Competency Path', 'verbose_name_plural': 'Competency Paths'},
        ),
        migrations.AlterModelOptions(
            name='mentor_grade',
            options={'verbose_name': 'Mentor Grade', 'verbose_name_plural': 'Mentor Grades'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='task_status',
            options={'verbose_name': 'Task Status', 'verbose_name_plural': 'Task Statuses'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='user_badges',
            options={'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='user_paths',
            options={'verbose_name': 'User Path', 'verbose_name_plural': 'User Paths'},
        ),
    ]
