# Generated by Django 5.2.7 on 2025-11-22 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_badges_options_alter_competency_paths_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Quiz question',
                'verbose_name_plural': 'Quiz questions',
            },
        ),
        migrations.CreateModel(
            name='Task_types',
            fields=[
                ('task_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Task_type',
                'verbose_name_plural': 'Task_types',
            },
        ),
        migrations.RemoveField(
            model_name='competency_paths',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='task_status',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='task_status',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='task_status',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='mentor',
        ),
        migrations.AddField(
            model_name='badges',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badge_icons/'),
        ),
        migrations.AddField(
            model_name='task_status',
            name='task_status_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='need_verification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='path_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user_badges',
            name='awarder_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='badges',
            name='badge_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='competency_paths',
            name='path_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='new_status',
            field=models.CharField(blank=True, choices=[('do zrobienia', 'Do Zrobienia'), ('w trakcie', 'W Trakcie'), ('do weryfikacji', 'Do Weryfikacji'), ('ukończone', 'Ukonczone')], default='do zrobienia', max_length=50),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='old_status',
            field=models.CharField(blank=True, choices=[('do zrobienia', 'Do Zrobienia'), ('w trakcie', 'W Trakcie'), ('do weryfikacji', 'Do Weryfikacji'), ('ukończone', 'Ukonczone')], default=django.db.models.deletion.SET_NULL, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_path', to='onboarding.competency_paths'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_badges',
            name='user_badge_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to='onboarding.competency_paths'),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_paths',
            name='user_path_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Quiz_answers',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=500)),
                ('correct', models.BooleanField(blank=True, default=django.db.models.deletion.SET_NULL, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='onboarding.quiz_question')),
            ],
            options={
                'verbose_name': 'Quiz answer',
                'verbose_name_plural': 'Quiz answers',
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_task', to='onboarding.tasks')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_quiz', to='onboarding.quizzes'),
        ),
        migrations.CreateModel(
            name='Task_type_quiz',
            fields=[
                ('task_quiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_task_type', to='onboarding.tasks')),
            ],
            options={
                'verbose_name': 'Task Type Quiz',
                'verbose_name_plural': 'Tasks Type Quiz',
            },
        ),
        migrations.CreateModel(
            name='Task_type_text',
            fields=[
                ('task_text_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_task_type', to='onboarding.tasks')),
            ],
            options={
                'verbose_name': 'Task Type Text',
                'verbose_name_plural': 'Tasks Type Text',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.task_types'),
        ),
        migrations.CreateModel(
            name='User_tasks',
            fields=[
                ('user_tasks_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_assigned', to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_to_user', to='onboarding.tasks')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_to_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Task',
                'verbose_name_plural': 'User Tasks',
            },
        ),
        migrations.CreateModel(
            name='User_grade',
            fields=[
                ('grade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_grades', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_grades', to=settings.AUTH_USER_MODEL)),
                ('user_task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_grades', to='onboarding.user_tasks')),
            ],
            options={
                'verbose_name': 'User Grade',
                'verbose_name_plural': 'User Grades',
            },
        ),
        migrations.AddField(
            model_name='task_status',
            name='user_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='onboarding.user_tasks'),
        ),
        migrations.DeleteModel(
            name='Mentor_grade',
        ),
    ]
