# Generated by Django 5.2.7 on 2026-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_quiz_question_task_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_answers',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='old_status',
            field=models.CharField(blank=True, choices=[('do zrobienia', 'Do Zrobienia'), ('w trakcie', 'W Trakcie'), ('do weryfikacji', 'Do Weryfikacji'), ('ukończone', 'Ukonczone')], default=None, max_length=50, null=True),
        ),
    ]
